### ISSUE TITLE
Error on Installation

### ISSUE THREAD

**Issue by millerdrew** [robbyronk/zonelist#1]
Hi @robbyronk !
Just tried to install but got this error:

```shell
16:32:56.892 [error] GenServer #PID<0.302.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection) lib/db_connection/connection.ex:148: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Zone.Repo couldn't be created: an exception was raised:
    ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
        (db_connection) lib/db_connection/connection.ex:148: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by robbyronk** [comment]
Hey Drew! Looks like Postgres isn’t running. Once I’m back at my computer I’ll share the docker command I’ve been using to create a local Postgres.

**Comment by robbyronk** [comment]
`docker run --rm --name zone_dev -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=zone_dev postgres`

Let me know if that doesn't work :)

**Comment by robbyronk** [comment]
Hey Drew,

Sorry for the radio silence for so long! I had to take a break.

I've updated ZoneList to use Vagrant and Virtualbox to create a local database. I've tested it on both Linux and Mac too. Try the [new instructions](https://github.com/robbyronk/zonelist) and let me know how it goes.
